<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.10">
  <POU Name="FB_ExDevUML_SM" Id="{0d23ae89-ec70-4541-86b1-c25e855b3f6c}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_ExDevUML_SM
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <StateChart>
        <XmlArchive>
          <Data>
            <o xml:space="preserve" t="UMLStateChart">
              <v n="Abortable">true</v>
              <v n="UseVarInstForMethods">false</v>
              <v n="StatesCount">0</v>
              <v n="HistoryCount">0</v>
              <v n="TransitionsCount">0</v>
              <v n="RegionsCount">0</v>
              <v n="TracesCount">0</v>
              <v n="StatesInitString">""</v>
              <v n="TransitionsInitString">""</v>
              <v n="RegionsInitString">""</v>
              <v n="StateNamesString">""</v>
              <n n="StateNamesInitString" />
              <v n="ForceActionRemove">false</v>
              <d n="RegionsWithStartStatesTable" t="Hashtable" ckt="Guid" cvt="Int32">
                <v>00000000-0000-0000-0000-000000000000</v>
                <v>1</v>
              </d>
              <d n="RegionsWithHistoryStatesTable" t="Hashtable" ckt="Guid" cvt="Int32">
                <v>00000000-0000-0000-0000-000000000000</v>
                <v>1</v>
              </d>
              <d n="RegionsWithEndStatesTable" t="Hashtable" />
              <n n="BreakPointGuids" />
              <v n="UmlEditorRestrictions" t="EditorRestrictions">None</v>
              <v n="DUTObjectGuid">{c9dec796-6e92-4749-aaba-c9e5b1c89d02}</v>
              <v n="DUTNamesObjectGuid">{70c832cb-3086-47aa-a84c-aabeba3f2510}</v>
              <v n="TraceObject">{00000000-0000-0000-0000-000000000000}</v>
              <v n="IsCompiling">false</v>
              <v n="HideLanguageModel">false</v>
              <v n="DefaultStateSizeX">62</v>
              <v n="DefaultStateSizeY">32</v>
              <v n="SuppressAutomaticLibraryLoading">false</v>
              <v n="DiagramName">"FB_ExDevUML_SM"</v>
              <v n="DiagramGuid">{0d23ae89-ec70-4541-86b1-c25e855b3f6c}</v>
              <v n="IsActionRemoving">false</v>
              <v n="ForceRepaintDiagram">false</v>
              <v n="Documentationdiagram">false</v>
              <v n="ApplicationGuidForDiagram">{00000000-0000-0000-0000-000000000000}</v>
              <v n="AutomaticLayOutHeightSpace">0</v>
              <v n="AutomaticLayOutWidthSpace">0</v>
              <d n="ElementObjects" t="Hashtable" ckt="Guid">
                <v>e016922a-d627-4e0c-910b-04a117346374</v>
                <o t="UMLStateChartElement">
                  <v n="StateChartGuid">{0d23ae89-ec70-4541-86b1-c25e855b3f6c}</v>
                  <v n="ImplicitStartStateType" t="ImplicitStartStateTypes">None</v>
                  <v n="EntryLocalVariableName">""</v>
                  <v n="EntryActionName">""</v>
                  <v n="EntryParametersString">""</v>
                  <v n="EntryActionText">""</v>
                  <v n="InjectedDoImplementationCode">""</v>
                  <v n="DoActionText">""</v>
                  <v n="ExitActionText">""</v>
                  <v n="DoLocalVariableName">""</v>
                  <v n="DoActionName">""</v>
                  <v n="DoParametersString">""</v>
                  <v n="ExitLocalVariableName">""</v>
                  <v n="ExitActionName">""</v>
                  <v n="ExitParametersString">""</v>
                  <v n="HasEntryAction">false</v>
                  <v n="HasDoAction">false</v>
                  <v n="HasExitAction">false</v>
                  <v n="PropertyID">0</v>
                  <v n="wasFork">false</v>
                  <d n="ActionList" t="Hashtable" />
                  <d n="PropertyList" t="Hashtable" />
                  <v n="ElementName">"BeamOff"</v>
                  <v n="MethodID">0</v>
                  <d n="MethodStereotypContainer" t="Hashtable" />
                  <o n="ElementVisualisation" t="UMLStateChartElementVisualisation">
                    <v n="ShowAttributes">true</v>
                    <v n="ShowMethods">true</v>
                    <v n="RepresentedElement">1</v>
                    <v n="IsElementVisible">true</v>
                    <v n="TopPosition">70</v>
                    <v n="LeftPosition">300</v>
                    <v n="WidthValue">99</v>
                    <v n="MinWidthValue">0</v>
                    <v n="Height">39</v>
                    <v n="MinHeight">0</v>
                    <v n="AutomaticLayout">false</v>
                    <d n="DockingPoints" t="Hashtable" />
                  </o>
                  <l2 n="VariableList" />
                  <n n="StereotypeContainer" />
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="bIsVisualisationChanged">false</v>
                  <v n="IsType" t="UMLType">UMLStateChartElement</v>
                  <v n="_MaxDoCycleCalls" t="Int16">32767</v>
                  <v n="DefaultCellSizeX">62</v>
                  <v n="DefaultCellSizeY">32</v>
                  <v n="IsDocumentation">false</v>
                  <v n="Area">{00000000-0000-0000-0000-000000000000}</v>
                  <v n="ParsedMethods">false</v>
                  <v n="ParsedProperties">false</v>
                  <v n="GeneratorId">0</v>
                  <v n="UserDefined">true</v>
                  <v n="ElementID">1</v>
                  <v n="ElementObjectGuid">{e016922a-d627-4e0c-910b-04a117346374}</v>
                  <v n="ParentGuid">{0d23ae89-ec70-4541-86b1-c25e855b3f6c}</v>
                  <v n="ContainerGuid">{00000000-0000-0000-0000-000000000000}</v>
                  <v n="ShowedStereotype">{00000000-0000-0000-0000-000000000000}</v>
                  <v n="ReplacewithImage">false</v>
                  <v n="AutomaticLayout">false</v>
                  <v n="PositionCounter">1L</v>
                  <v n="UMLPosition">-1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">-13447886</v>
                  <v n="ZOrder">3U</v>
                </o>
                <v>32f52e22-57ae-4788-b863-ccc2e0874727</v>
                <o t="UMLStateChartPseudoElement">
                  <o n="ElementVisualisation" t="UMLStateChartDiagramElementVisualisationDot">
                    <v n="ShowAttributes">true</v>
                    <v n="ShowMethods">true</v>
                    <v n="RepresentedElement">1</v>
                    <v n="IsElementVisible">true</v>
                    <v n="TopPosition">92</v>
                    <v n="LeftPosition">170</v>
                    <v n="WidthValue">20</v>
                    <v n="MinWidthValue">0</v>
                    <v n="Height">20</v>
                    <v n="MinHeight">0</v>
                    <v n="AutomaticLayout">false</v>
                    <d n="DockingPoints" t="Hashtable" />
                  </o>
                  <v n="Condition">""</v>
                  <v n="HistoryType" t="HistoryTypes">None</v>
                  <v n="StateChartGuid">{0d23ae89-ec70-4541-86b1-c25e855b3f6c}</v>
                  <v n="EntryLocalVariableName">""</v>
                  <v n="EntryActionName">""</v>
                  <v n="EntryParametersString">""</v>
                  <v n="EntryActionText">""</v>
                  <v n="InjectedDoImplementationCode">""</v>
                  <v n="DoActionText">""</v>
                  <v n="ExitActionText">""</v>
                  <v n="DoLocalVariableName">""</v>
                  <v n="DoActionName">""</v>
                  <v n="DoParametersString">""</v>
                  <v n="ExitLocalVariableName">""</v>
                  <v n="ExitActionName">""</v>
                  <v n="ExitParametersString">""</v>
                  <v n="HasEntryAction">false</v>
                  <v n="HasDoAction">false</v>
                  <v n="HasExitAction">false</v>
                  <v n="PropertyID">0</v>
                  <v n="wasFork">false</v>
                  <d n="ActionList" t="Hashtable" />
                  <d n="PropertyList" t="Hashtable" />
                  <v n="ElementName">"StartState1"</v>
                  <v n="MethodID">0</v>
                  <d n="MethodStereotypContainer" t="Hashtable" />
                  <l2 n="VariableList" />
                  <n n="StereotypeContainer" />
                  <v n="HasGraphicalRepresentation">true</v>
                  <v n="bIsVisualisationChanged">false</v>
                  <v n="IsType" t="UMLType">UMLStateChartStartState</v>
                  <v n="_MaxDoCycleCalls" t="Int16">32767</v>
                  <v n="DefaultCellSizeX">20</v>
                  <v n="DefaultCellSizeY">20</v>
                  <v n="IsDocumentation">false</v>
                  <v n="Area">{00000000-0000-0000-0000-000000000000}</v>
                  <v n="ParsedMethods">false</v>
                  <v n="ParsedProperties">false</v>
                  <v n="GeneratorId">0</v>
                  <v n="UserDefined">true</v>
                  <v n="ElementID">1</v>
                  <v n="ElementObjectGuid">{32f52e22-57ae-4788-b863-ccc2e0874727}</v>
                  <v n="ParentGuid">{0d23ae89-ec70-4541-86b1-c25e855b3f6c}</v>
                  <v n="ContainerGuid">{00000000-0000-0000-0000-000000000000}</v>
                  <v n="ShowedStereotype">{00000000-0000-0000-0000-000000000000}</v>
                  <v n="ReplacewithImage">false</v>
                  <v n="AutomaticLayout">false</v>
                  <v n="PositionCounter">1L</v>
                  <v n="UMLPosition">-1L</v>
                  <v n="IsModified">false</v>
                  <v n="ARGBElementColor">0</v>
                  <v n="ZOrder">1U</v>
                </o>
              </d>
              <v n="FirstPaint">true</v>
              <v n="NextElementID">0</v>
              <d n="UMLRelationObjects" t="Hashtable" />
              <v n="NextRelationID">0</v>
              <v n="DefaultAutomaticLayout">false</v>
              <o n="ClassDiagrammProperties" t="UMLDiagramProperties">
                <v n="ArrayOfPointerToClassPresentation" t="RelationTypes">Empty</v>
                <v n="ArrayOfClassPresentation" t="RelationTypes">Empty</v>
                <v n="ArrayOfInterfacePresentation" t="RelationTypes">Empty</v>
                <v n="ArrayOfInterfaceAggregationPresentation" t="RelationTypes">Empty</v>
                <v n="PointerToClassPresentation" t="RelationTypes">Empty</v>
                <v n="ClassPresentation" t="RelationTypes">Empty</v>
                <v n="InterfacePresentation" t="RelationTypes">Empty</v>
                <v n="InterfaceAggregationPresentation" t="RelationTypes">Empty</v>
                <v n="ShowRoleNames">true</v>
                <v n="ShowCardinalities">true</v>
                <v n="ShowRelationNames">true</v>
                <v n="ShowAttributesinClasses">false</v>
                <v n="ShowMethodsInClasses">false</v>
                <v n="ParametersMaximumLength">20</v>
              </o>
              <v n="IsFastStateDiagram">false</v>
              <l n="StereoTypeProfile" t="ArrayList" />
              <v n="RelationRoleID">1</v>
              <d n="PositionSerialization" t="Hashtable" ckt="Int64" cvt="Guid">
                <v>3</v>
                <v>e016922a-d627-4e0c-910b-04a117346374</v>
                <v>2</v>
                <v>e016922a-d627-4e0c-910b-04a117346374</v>
                <v>1</v>
                <v>32f52e22-57ae-4788-b863-ccc2e0874727</v>
              </d>
            </o>
          </Data>
          <TypeList>
            <Type n="ArrayList">System.Collections.ArrayList</Type>
            <Type n="Boolean">System.Boolean</Type>
            <Type n="EditorRestrictions">{1ca7a370-7213-48b2-9df6-3ac7e85f0c68}</Type>
            <Type n="Guid">System.Guid</Type>
            <Type n="Hashtable">System.Collections.Hashtable</Type>
            <Type n="HistoryTypes">{3534dff0-3cd3-4ab6-8e74-b81ff8613005}</Type>
            <Type n="ImplicitStartStateTypes">{159536e2-c3a1-4501-a760-7b5009964f41}</Type>
            <Type n="Int16">System.Int16</Type>
            <Type n="Int32">System.Int32</Type>
            <Type n="Int64">System.Int64</Type>
            <Type n="RelationTypes">{f5146002-a332-47c0-9d9a-7997d539e6a9}</Type>
            <Type n="String">System.String</Type>
            <Type n="UInt32">System.UInt32</Type>
            <Type n="UMLDiagramProperties">{71bc64fb-98e8-4f9a-b2ec-0da66cfaa0a0}</Type>
            <Type n="UMLStateChart">{9b0dd937-6691-44b8-b0c0-27601a5e098a}</Type>
            <Type n="UMLStateChartDiagramElementVisualisationDot">{573ce27a-c0d4-453b-8ffd-6d125a13ad66}</Type>
            <Type n="UMLStateChartElement">{a9cbb7e7-7aa8-4772-a0f9-efee80bd48b2}</Type>
            <Type n="UMLStateChartElementVisualisation">{861a8beb-602e-4017-bf45-a602984c46fe}</Type>
            <Type n="UMLStateChartPseudoElement">{3569ebb7-c8a3-4ab4-b440-d179b9e0fe9b}</Type>
            <Type n="UMLType">{0197b136-405a-42ee-bb27-fd08b621d0cf}</Type>
          </TypeList>
        </XmlArchive>
      </StateChart>
    </Implementation>
  </POU>
</TcPlcObject>