<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.12">
  <POU Name="PMPS_Arbiter" Id="{91ae890b-11cc-4d41-83ec-edc5b802c784}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PMPS_Arbiter
VAR
	
	
	fbMachine	:	FB_MachineSimulator;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
//Execute arbiter
fbArbiter();

//Machine simulator
fbMachine(
	i_stAssertedParams := fbArbiter.q_stBeamParams,
	q_stMachineParams => PMPS_GVL_BeamParams.stCurrentBeamParameters
	);]]></ST>
    </Implementation>
    <LineIds Name="PMPS_Arbiter">
      <LineId Id="75" Count="0" />
      <LineId Id="16" Count="0" />
      <LineId Id="74" Count="0" />
      <LineId Id="67" Count="1" />
      <LineId Id="66" Count="0" />
      <LineId Id="71" Count="2" />
    </LineIds>
  </POU>
</TcPlcObject>