<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.0">
  <POU Name="FB_BPRequestor" Id="{7bca38cb-b015-0bee-2b8d-d1d37159090d}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_BPRequestor
VAR_INPUT
	stReqBP	:	ST_ReqBeamParams;
END_VAR
VAR_OUTPUT
	q_stReqBP :	ST_ReqBeamParams;
	q_ReqAtt  : REAL;
END_VAR
VAR
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[q_stReqBP := stReqBP;
q_ReqAtt := stReqBP.fAtt;]]></ST>
    </Implementation>
    <LineIds Name="FB_BPRequestor">
      <LineId Id="9" Count="0" />
      <LineId Id="23" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>