<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.12">
  <POU Name="FB_FastFault" Id="{a7225e03-a5d8-094a-35f2-8e6e41471d21}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_FastFault
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_FastFault">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>