<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.0">
  <POU Name="Fast_Faults_Setup" Id="{bdc9fda1-3ab8-0d1a-09bd-274a15fdc835}" SpecialFunc="None">
    <Declaration><![CDATA[// Run at the start of each cycle

PROGRAM Fast_Faults_Setup
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[g_FastFaultOutput1();]]></ST>
    </Implementation>
    <LineIds Name="Fast_Faults_Setup">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>