<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.12">
  <POU Name="Fast_Faults" Id="{bdc9fda1-3ab8-0d1a-09bd-274a15fdc835}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM Fast_Faults
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[g_FastFaultOutput1();]]></ST>
    </Implementation>
    <LineIds Name="Fast_Faults">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>