<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.12">
  <POU Name="MachineSimulation" Id="{215532fb-b2c1-07b9-12dd-bf8b9df2fcb5}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MachineSimulation
VAR
	fbMachine	:	FB_MachineSimulator;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[//Machine simulator
fbMachine(
	i_stAssertedParams := g_fbArbiter.q_stBeamParams,
	q_stMachineParams => PMPS_GVL_BeamParams.stCurrentBeamParameters,
	i_xFault	:= NOT GVL.g_FastFaultOutput1.q_xFastFaultOut
	);]]></ST>
    </Implementation>
    <LineIds Name="MachineSimulation">
      <LineId Id="6" Count="4" />
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>