<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.12">
  <POU Name="FB_BPRequestor_Test" Id="{2e76b681-c0a9-0f76-29da-160e72c43f83}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'call_after_init'}
FUNCTION_BLOCK FB_BPRequestor_Test EXTENDS FB_TestSuite IMPLEMENTS I_RunnableTestSuite
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	fbAssert : TcUnit.FB_Assert;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="BPRequestorSafeGuardFunctionality" Id="{998205c2-d03c-03ca-3e9d-2b3342d79f18}">
      <Declaration><![CDATA[METHOD PRIVATE BPRequestorSafeGuardFunctionality
VAR_INPUT
END_VAR
VAR
	fbBPR	:	FB_BPRequestor;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[TEST('PEWatcherBasicFunction');

//Clear FFO fault to start
]]></ST>
      </Implementation>
    </Method>
    <Method Name="FB_init" Id="{72aa7fd8-8af4-04a7-1d17-210644634f4a}">
      <Declaration><![CDATA[METHOD FB_init : BOOL
VAR_INPUT
	bInitRetains : BOOL; // if TRUE, the retain variables are initialized (warm start / cold start)
	bInCopyCode : BOOL;  // if TRUE, the instance afterwards gets moved into the copy code (online change)
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[SUPER^.RegisterTestSuite(THIS^);

]]></ST>
      </Implementation>
    </Method>
    <Method Name="RunTests" Id="{e51cd65a-564c-097b-0d67-be53e5d72842}">
      <Declaration><![CDATA[METHOD RunTests : TCUNIT.E_TestSuiteRunState
]]></Declaration>
      <Implementation>
        <ST><![CDATA[BPRequestorSafeGuardFunctionality();

RunTests := TcUnit.E_TestSuiteRunState.FINISHED;]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_BPRequestor_Test">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_BPRequestor_Test.BPRequestorSafeGuardFunctionality">
      <LineId Id="144" Count="0" />
      <LineId Id="176" Count="1" />
      <LineId Id="221" Count="0" />
    </LineIds>
    <LineIds Name="FB_BPRequestor_Test.FB_init">
      <LineId Id="7" Count="0" />
      <LineId Id="9" Count="0" />
      <LineId Id="8" Count="0" />
    </LineIds>
    <LineIds Name="FB_BPRequestor_Test.RunTests">
      <LineId Id="4" Count="0" />
      <LineId Id="6" Count="0" />
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>