<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="FB_BeamParamFanout_Test" Id="{35b09878-0c41-0a31-0f77-f3e1a5b30d81}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'call_after_init'}
FUNCTION_BLOCK FB_BeamParamFanout_Test EXTENDS TcUnit.FB_TestSuite
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR

END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="BPFanoutSafeguard" Id="{8f6e225f-b54c-0582-05a2-5752ed28fff5}">
      <Declaration><![CDATA[METHOD PRIVATE BPFanoutSafeguard
VAR_INPUT
END_VAR
VAR
	fbBPF	:	FB_BeamParamFanout;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[TEST('Reset validity bool if interface invalid');
fbBPF.xTxPDO_state := 0; //OP
fbBPF();
AssertTrue(fbBPF.stBP.xValidToggle,
	'Does not start valid');
	
fbBPF.xTxPDO_state := 1; // Not op	
	
AssertFalse(fbBPF.stBP.xValidToggle,
	'Does not indicate invalid after IF goes non-op');

]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_BeamParamFanout_Test">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_BeamParamFanout_Test.BPFanoutSafeguard">
      <LineId Id="144" Count="0" />
      <LineId Id="233" Count="4" />
      <LineId Id="239" Count="1" />
      <LineId Id="238" Count="0" />
      <LineId Id="241" Count="0" />
      <LineId Id="227" Count="0" />
      <LineId Id="177" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>