<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.12">
  <POU Name="FB_BreakTheArbiter" Id="{572de4b8-f6c3-0c43-352b-59452dfd0cf0}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_BreakTheArbiter
VAR_INPUT
	
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_BreakTheArbiter">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>