<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="FB_eVWithinSpec_Test" Id="{b622c686-f9dd-0ccb-3e3a-bfb750a08cb0}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'call_after_init'}
FUNCTION_BLOCK FB_eVWithinSpec_Test EXTENDS TcUnit.FB_TestSuite
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[evWithinRangeChecks();]]></ST>
    </Implementation>
    <Method Name="evWithinRangeChecks" Id="{1d6c611b-6bb7-0728-3075-755617dbc45a}">
      <Declaration><![CDATA[METHOD evWithinRangeChecks
VAR_INPUT
END_VAR
VAR

END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[TEST('evWithinRangeChecks');
	
//Upper limit equal
AssertTrue(
	F_eVWithinSpec(300, 2#0000_0000_0000_0010),
	'Upper limit not inclusive');
//Lower limit equal
AssertTrue(
	F_eVWithinSpec(300, 2#0000_0000_0000_0100),
	'Lower limit not inclusive');
//Out of range
AssertFalse(
	F_eVWithinSpec(300.1, 2#0000_0000_0000_0010),
	'Out of range failed, whatever you did, it broke this really bad.');
//Negative eV
AssertFalse(
	F_eVWithinSpec(-300, 16#FFFF),
	'Working with antimatter? Negative eV should not be acceptable.');
//Upper unallocated range
AssertFalse(
	F_eVWithinSpec(1700, 2#1000_0000_0000_0000),
	'eV range should not evaluate past 1.6keV');
	
TEST_FINISHED('');]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_eVWithinSpec_Test">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_eVWithinSpec_Test.evWithinRangeChecks">
      <LineId Id="33" Count="0" />
      <LineId Id="38" Count="0" />
      <LineId Id="30" Count="0" />
      <LineId Id="77" Count="0" />
      <LineId Id="86" Count="1" />
      <LineId Id="76" Count="0" />
      <LineId Id="88" Count="1" />
      <LineId Id="79" Count="0" />
      <LineId Id="78" Count="0" />
      <LineId Id="90" Count="1" />
      <LineId Id="81" Count="0" />
      <LineId Id="80" Count="0" />
      <LineId Id="92" Count="1" />
      <LineId Id="83" Count="0" />
      <LineId Id="82" Count="0" />
      <LineId Id="94" Count="1" />
      <LineId Id="85" Count="0" />
      <LineId Id="101" Count="0" />
      <LineId Id="84" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>